"""empty message

Revision ID: 49bd3c6ad2c8
Revises: 
Create Date: 2022-12-05 15:05:53.112705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49bd3c6ad2c8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('create_playlist',
    sa.Column('idCreating_playlist', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('idCreating_playlist')
    )
    op.create_table('song',
    sa.Column('idsong', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('artist', sa.String(length=45), nullable=False),
    sa.Column('playlistId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['playlistId'], ['create_playlist.idCreating_playlist'], ),
    sa.PrimaryKeyConstraint('idsong')
    )
    op.create_table('user',
    sa.Column('iduser', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=45), nullable=False),
    sa.Column('email', sa.String(length=45), nullable=False),
    sa.Column('phone', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(length=45), nullable=False),
    sa.Column('userStatus', sa.String(length=45), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('playlist_Id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['playlist_Id'], ['create_playlist.idCreating_playlist'], ),
    sa.PrimaryKeyConstraint('iduser')
    )
    op.create_table('playlist_has_song',
    sa.Column('Creat_playlist_id', sa.Integer(), nullable=True),
    sa.Column('song_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Creat_playlist_id'], ['create_playlist.idCreating_playlist'], ),
    sa.ForeignKeyConstraint(['song_id'], ['song.idsong'], )
    )
    op.create_table('type',
    sa.Column('idtype_playlist', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('playlist_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['playlist_id'], ['create_playlist.idCreating_playlist'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.iduser'], ),
    sa.PrimaryKeyConstraint('idtype_playlist')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('type')
    op.drop_table('playlist_has_song')
    op.drop_table('user')
    op.drop_table('song')
    op.drop_table('create_playlist')
    # ### end Alembic commands ###
